# Generated by Django 3.2.2 on 2021-05-21 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gravitacionais', '0002_alter_gravitacional_nome_gravitacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravitacional',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
