# Generated by Django 3.2.2 on 2021-05-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravitacionais', '0003_gravitacional_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gravitacional',
            name='nome_gravitacional',
        ),
        migrations.AlterField(
            model_name='gravitacional',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
