# Generated by Django 3.2.2 on 2021-06-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gravitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=250)),
                ('linha', models.CharField(max_length=10)),
                ('posto', models.CharField(max_length=10)),
                ('galpao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=100)),
                ('codigo_peca', models.CharField(max_length=20, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('embalagem', models.CharField(default='', max_length=10)),
                ('gravitacional_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecas.gravitacional')),
                ('peca_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecas.peca')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(default='requisitado', max_length=10)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecas.aplicacao')),
            ],
        ),
    ]
