# Generated by Django 3.2.2 on 2021-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='codigo_peca',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
