# Generated by Django 3.2.2 on 2021-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0002_alter_peca_codigo_peca'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='embalagem',
            field=models.CharField(default='', max_length=10),
        ),
    ]
