# Generated by Django 3.2.2 on 2021-05-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0003_aplicacao_embalagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacao',
            name='quantidade',
        ),
    ]
